### PR TITLE
updated app setup in readme

### PR DESCRIPTION
**Pull request by plemiszki**
Changes proposed in this pull request:

- clarified documentation, as referenced in https://github.com/18F/dolores-landingham-bot/pull/172#discussion_r63910863

### CODE REVIEW

**Comment by afeld** [comment]
Going to defer to @jessieay or someone else more familiar with the project on this one. If Foreman is used in all environments, it seems that the entire line can be removed from CONTRIBUTING. If it's only used for development, I think it's fine for the project to be opinionated and say "run this project in development using Foreman", and just having Foreman in the `development` group of the Gemfile.

/cc https://github.com/18F/dolores-landingham-bot/issues/179

**Comment by plemiszki** [comment]
Yes, that's probably true. I removed the line. The gem is used in production however, so I didn't move it to the development group.

**Comment by afeld** [comment]
Looks good to me! Will wait on @jessieay to merge.

**Comment by jessieay** [comment]
@plemiszki you're right, foreman is used in prod. That comment in `CONTRIBUTING` is from a boilerplate rails app setup that didn't use foreman in production. Mind removing 

> If you don't have foreman, see Foreman's install instructions. It is purposefully excluded from the project's Gemfile.

while we're here?

thanks for the pR!

**Comment by plemiszki** [comment]
@jessieay sorry for the delay. I have removed the comment. Please let me know if everything looks ok now.

**Comment by jessieay** [comment]
there was a merge conflict so I pulled your branch down and made a few tweaks before merging. Merged at https://github.com/18F/dolores-landingham-bot/commit/a2f6a0ff888c3ffd7e3ae71449f856bbe2c23d9c - thank you very much!!

**Pull request closed without merging**
