### PR TITLE
Find or create user record during auth

### PR DESCRIPTION
**Pull request by jessieay**
* Next step is to give admin users certain abilities
* Part of https://github.com/18F/dolores-landingham-bot/issues/53

### CODE REVIEW

**Comment by jessieay** [comment]
Failing specs here will be fixed via https://github.com/18F/dolores-landingham-bot/pull/135

cc @gemfarmer

**Comment by jessieay** [comment]
@ccostino this is ready for review if you have a minute :)

**Comment by gemfarmer** [comment]
@jessieay looks good! 

Though, I'm not totally sure how much this changes things. People already couldn't make changes unless they had a `gsa.gov` email. I guess it is another line of defense? Or could someone hit the api without logging in?

**Comment by jessieay** [comment]
@gemfarmer this PR is making it so that we save users in the DB, but there are no user-facing changes.

My next step is going to be to actually update the permissions based on whether a user is an admin or not so we can give admins specific abilities. Without users in the DB, we couldn't have permission levels because all we had as a token saved in a cookie.

Thanks for the review!

**Comment by gemfarmer** [comment]
@jessieay based on @melodykramer's comment [here](https://github.com/18F/dolores-landingham-bot/issues/53#issuecomment-149877620) I thought we were going to be allowing everyone (with a gsa email) to edit?

**Comment by jessieay** [comment]
@gemfarmer per Melody's comment in the linked issue, we are going to limit *some* actions to admins only, but all people will be able to do other things. :rocket:

**Comment by gemfarmer** [comment]
Ah I see that now. Thanks for the clarification.

**Pull request merged**
