### PR TITLE
Fixed sent messages filter, re-introduced pagination

### LINKED ISSUE #137: Filter for sent schedule messages is broken.
Now that SentScheduleMessages is back up, it is clear that the filter isn't working. Even though it was at one point. sigh

### PR DESCRIPTION
**Pull request by gemfarmer**
Fixes #137 

This PR
* fixes the SentScheduledMessages filter
* re-introduces pagination, ordering with unique keys, per [Moncef's comment](https://github.com/18F/dolores-landingham-bot/issues/128#issuecomment-171047847)
 
@jessieay or @ccostino once the test pass, care to review?

### CODE REVIEW

**Comment by ccostino** [comment]
Awesome, thanks @gemfarmer!  I'll try and take a look tonight before finishing for the day, but if @jessieay or someone can get to it sooner that's fine too. :-)

**Comment by ccostino** [comment]
Uh oh, looks like a Rails update is in order based on the Travis messages regarding security vulnerabilities.

**Comment by gemfarmer** [comment]
updated `actionpack` to 4.2.5.1, but now seeing this error:
`
WARNING: The next major version of capybara-webkit will require at least version 5.0 of Qt. You're using version 4.8.1.
`

:scratch-head

**Comment by jessieay** [comment]
@gemfarmer that error is unrelated. we should update all of rails to 4.2.5.1 not just actionpack. there were a bunch of security issues released yesterday for 4.2.5

**Comment by gemfarmer** [comment]
@jessieay I updated rails to 4.2.5.1 with my last commit. Did you mean that there are security issues for 4.2.4, or were there also security issues for 4.2.5. We could update to a later version. 

The capybara issue is unrelated to this PR, but I figured out what is going on, so I'll just tack it on to this one, if that's alright.

**Comment by gemfarmer** [comment]
Hmm I have dolores running with qt5 locally, but I haven't figured out how to get it to pass Travis.

**Comment by jessieay** [comment]
the issue you are seeing seems related to shoulda matchers. let's upgrade the gemfile in a separate branch

**Comment by jessieay** [comment]
@gemfarmer just opened https://github.com/18F/dolores-landingham-bot/pull/139 for Gemfile updates. No other gemfile updates should be required for this PR, so you can git checkout Gemfile.lock

**Comment by gemfarmer** [comment]
@jessieay sounds good!

**Comment by jessieay** [comment]
merged my branch, so if you rebase this should be :green_heart:  -- I can review it in an hour or so!

**Comment by gemfarmer** [comment]
@jessieay Cool. I just rebased and squashed the commits.

**Comment by ccostino** [comment]
@gemfarmer: I just took a quick look too, this is awesome, thank you!

**Comment by gemfarmer** [comment]
@ccostino merged and pushed to `dolores-staging` and `dolores-app`.

**Pull request merged**
