### PR TITLE
Tiny explanation of the reference

### PR DESCRIPTION
**Pull request by brittag**
Adding a line to give credit for the name and photo. :)

### CODE REVIEW

**Comment by wslack** [comment]
LGTM but checks aren't completed yet :)

**Comment by stvnrlly** [comment]
The tests pass, but there's a dependency that needs updating. I think it's up to @jessieay to determine whether this can be merged before that.

**Comment by jessieay** [comment]
Hey @brittag thanks for opening this PR!

If you pull in the recent updates from master the build should pass (I upgraded some libs just now)

**Comment by brittag** [comment]
Done! Looks like the checks pass now, thanks @jessieay. :)

**Comment by jessieay** [comment]
Thanks, @brittag ! merged

**Pull request merged**
