### PR TITLE
Remove references to Waffle

### PR DESCRIPTION
**Pull request by jessieay**
* Haven't been using Waffle much. GH Issues work just fine

### CODE REVIEW

**Comment by jessieay** [comment]
cc @gemfarmer @ccostino

**Comment by ccostino** [comment]
@jessieay and @gemfarmer:  I'm fine with this as it cuts down on the signal/noise ratio with things to check, especially given that this is a small project with no dedicated team at the moment.  Thanks, @jessieay!  If @gemfarmer has no qualms then go ahead and merge.

**Comment by gemfarmer** [comment]
@jessieay @ccostino no qualms here.

**Comment by jessieay** [comment]
@ccostino @gemfarmer cool, merged!

**Pull request merged**
