### PR TITLE
User can update scheduled messages

### PR DESCRIPTION
**Pull request by jessieay**
* Edit title/body

### CODE REVIEW

**Comment by jessieay** [comment]
@gemfarmer

**Comment by gemfarmer** [comment]
I'm now seeing errors when I try to view all messages
screen shot 2015-09-11 at 12 35 43 pm

**Comment by gemfarmer** [comment]
This is after running `rake db:migate`

**Comment by jessieay** [comment]
@gemfarmer restart server?

**Comment by gemfarmer** [comment]
@jessieay Works on my end :) Feel free to squash and merge!

**Comment by jessieay** [comment]
@gemfarmer thanks! :bug:

**Pull request merged**
