### PR TITLE
[Fixes #130] Add dependent:destroy to relations

### LINKED ISSUE #130: Sent Schedule Messages bug
If you go to the [sent scheduled messages view](https://dolores-app.18f.gov/sent_scheduled_messages), the app errors out. The logs are below. I'm pretty sure this because the view is looking for the `slack_username` of an employee that no longer has a record. The `sent_scheduled_messsages` model [delegates](https://github.com/18F/dolores-landingham-bot/blob/master/app/models/sent_scheduled_message.rb#L11) finding an employee via its `employee_id` field. 

Sooo we need some way to catch this and not display the record if the employee has been deleted. Or display the record without an associated `slack_username`.

```
Rendered sent_scheduled_messages/index.html.erb within layouts/application (146.4ms)
2016-01-14T12:06:35.03-0700 [App/0]      OUT 19:06:35 web.1    | Completed 500 Internal Server Error in 147ms (ActiveRecord: 68.9ms)
2016-01-14T12:06:35.03-0700 [App/0]      OUT 19:06:35 web.1    | 
2016-01-14T12:06:35.03-0700 [App/0]      OUT 19:06:35 web.1    | ActionView::Template::Error (SentScheduledMessage#slack_username delegated to employee.slack_username, but employee is nil: #<SentScheduledMessage id: 941, created_at: "2016-01-11 20:13:37", updated_at: "2016-01-11 20:13:37", employee_id: 52, error_message: "", message_body: "From your coworker *Liz Goodman*: \"If you get a tr...", scheduled_message_id: 41, sent_on: "2016-01-11", sent_at: "2000-01-01 20:13:37">):
2016-01-14T12:06:35.03-0700 [App/0]      OUT 19:06:35 web.1    |     23: 
2016-01-14T12:06:35.03-0700 [App/0]      OUT 19:06:35 web.1    |     24:   <% @sent_scheduled_messages.each do |sent_message| %>
2016-01-14T12:06:35.03-0700 [App/0]      OUT 19:06:35 web.1    |     25:     <tr>
2016-01-14T12:06:35.03-0700 [App/0]      OUT 19:06:35 web.1    |     26:       <td><%= sent_message.slack_username %></td>
2016-01-14T12:06:35.03-0700 [App/0]      OUT 19:06:35 web.1    |     27:       <td><%= sent_message.sent_on %></td>
2016-01-14T12:06:35.03-0700 [App/0]      OUT 19:06:35 web.1    |     28:       <td><%= display_local_time_zone(sent_message) %></td>
2016-01-14T12:06:35.03-0700 [App/0]      OUT 19:06:35 web.1    |     29:       <td><%= truncate(sent_message.message_body, length: 50, separator: ' ') %></td>
2016-01-14T12:06:35.03-0700 [App/0]      OUT 19:06:35 web.1    |   app/models/sent_scheduled_message.rb:11:in `rescue in slack_username'
2016-01-14T12:06:35.03-0700 [App/0]      OUT 19:06:35 web.1    |   app/models/sent_scheduled_message.rb:11:in `slack_username'
```

### PR DESCRIPTION
**Pull request by jessieay**
* Fixes issue where deleting an employee breaks sent scheduled message page
* Use paranoia gem to soft delete objects
* https://github.com/18F/dolores-landingham-bot/issues/130

### CODE REVIEW

**Comment by gemfarmer** [comment]
@jessieay I am testing locally and still running into the same bug. I am deleting employees who have already received a message. Is there something that I am missing?

**Comment by jessieay** [comment]
@gemfarmer ah ha! you found a bug. I put the `dependent: :destroy` on the `belongs_to` instead of where it belonged on the has_many (if it s belongs to, the employee for a sent scheduled message is deleted when the sent scheduled message is deleted -- no bueno)

fixed at d9b164c

**Comment by gemfarmer** [comment]
@jessieay I am still receiving the error. Could it be that adding the `paranoia` gem will help with future issues, but isn't addressing the bug we are seeing with previously deleted records?

**Comment by jessieay** [comment]
ah yes, @gemfarmer this will not address previous issues. those records will need to be deleted manually. gonna merge this!

**Comment by gemfarmer** [comment]
:+1: Great!

**Pull request merged**
