### PR TITLE
Update nokogiri

### PR DESCRIPTION
**Pull request by jessieay**
* To fix Travis build (security concern w old version)
* Source: https://github.com/sparklemotion/nokogiri/issues/1374

### CODE REVIEW

**Comment by jessieay** [comment]
cc @monfresh @ccostino

**Comment by monfresh** [comment]
:+1:

**Comment by jessieay** [comment]
@monfresh we usually merge for ourselves on this project. :) thanks for taking a look!

**Comment by monfresh** [comment]
Ah! Will remember that next time.

**Comment by jessieay** [comment]
@monfresh hard to remember with all of these different flows on different projects! If only there were a working group devoted to code review process.... :imp:

**Pull request merged**
